### ISSUE TITLE
View All Heroes (GET)

### ISSUE THREAD

**Issue by BrainCodeJockey** [Hirnstromwelle/Sprite-Branch#1]
**As a User**
**I need** the ability to view a list of all heroes in my Visual Novel,
**in order to** have a comprehensive overview of all created heroes.

## Description
Implement a feature that allows users to retrieve and view a list of all heroes in the Visual Novel from the backend and frondend.

## Acceptance Criteria

- [x] Create a GET "/api/heroes" endpoint to fetch all heroes from the backend.
- [x] Display the list of all heroes on the homepage of the frontend.

## Tasks

(for the development team)

- [x] Create a Model with "Id, Name, and inventory" for each hero.
- [x] Create a "SavedGames" component in the UI.
- [x] Implement a GET request to retrieve all heroes from the backend.
- [x] Update the frontend to display the list of heroes.
- [x] Implement Unit and Integration Tests for the new functionality.
- [x] Add some styling for the hero list.
