### ISSUE TITLE
Delete a Hero (DELETE)

### ISSUE THREAD

**Issue by BrainCodeJockey** [Hirnstromwelle/Sprite-Branch#3]
**As a User**
**I need** to remove a hero from my Visual Novel
**to be able to** manage the story and characters.

#### Description
Enable users to delete a hero from the database via the frontend.

#### Acceptance Criteria

- [x] Create a DELETE Endpoint "/api/heroes/{id}" to delete a hero in the backend.
- [x] Integrate a delete function in the frontend allowing the user to select and remove a hero from the list.

#### Tasks

- [x] Implement the DELETE request to delete the hero in the backend.
- [x] Update the frontend to enable the delete functionality for heroes.
- [x] Implement Unit and Integration Tests for the delete functionality.
